Adds "option push_timeout" to allow more time for curl.
wlanslovenija/nodewatcher-agent pull request #3
Opened 2017-05-09 01:37 UTC by wylis-hodor

Also adds log of curl ERRORBUFFER in SSL_CONNECT_ERROR case.

2017-05-09 01:51 UTC, mitar commented on modules/http_push.c
> +        errbuf[0] = 0;
I would prefer `'\0'` here, as style.

2017-05-09 01:52 UTC, mitar commented on modules/http_push.c
> +        if (timeout < 5) {
Maybe `timeout == 0`.

2017-05-09 01:54 UTC, wylis-hodor commented on modules/http_push.c
> +        if (timeout < 5) {
Is that what nw_uci_get_int() returns if its not set?

2017-05-09 01:56 UTC, mitar commented on modules/http_push.c
> +        if (timeout < 5) {
Yes, it seems so.

2017-05-09 02:00 UTC, wylis-hodor commented on modules/http_push.c
> +        if (timeout < 5) {
OK I see it. I agree "== 0" looks good.  I will make these changes.

2017-05-09 08:34 UTC, kostko requested changes
Looks good, only a few minor comments need to be addressed.

2017-05-09 08:34 UTC, kostko commented on modules/http_push.c
> +        /* provide a buffer to store errors in */
Please fix comments so they start with a capital letter and end with a dot (also below).

2017-05-09 08:34 UTC, kostko commented on modules/http_push.c
> +        errbuf[0] = 0;
I agree.

2017-05-09 08:34 UTC, kostko commented on modules/http_push.c
> +              syslog(LOG_WARNING, "buf: %s", errbuf);
Can you change the warning to be something more descriptive? E.g., `http-push: SSL connect error: %s`?

2017-05-09 08:34 UTC, kostko commented on modules/http_push.c
> +              syslog(LOG_WARNING, "err: %s", curl_easy_strerror(result));
Can you change the warning to be something more descriptive? E.g., http-push: SSL connect error: %s?

2017-05-09 08:34 UTC, kostko commented on modules/http_push.c
> +        if (timeout < 5) {
Yes, this should be changed.

2017-05-09 21:24 UTC, wylis-hodor commented
I squashed my commits from this review into the original commit.  I am not sure if you can see the edits now or if i should submit a new pull request and close this one.  I guess i should have just committed the edits and let you squash.

2017-05-09 21:31 UTC, mitar commented
Yes, no worries about squashing. You can do it at the end, or we can do it when merging.

2017-05-10 06:59 UTC, kostko approved these changes
Looks good!

2017-05-10 07:00 UTC, merged